services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - npm_network

networks:
  npm_network:
    external: true